---
title: "Chapter 2 Lecture Code"
author: "Ali Raisolsadat"
date: "2025-10-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Part 4
```{r}
# slide 7 algorithm
set.seed(123)  # for reproducibility

# Parameters
N <- rpois(1, 50)
X <- runif(N, min = 0, max = 10)
Y <- rep(0, N)

# plot
plot(X, Y,
     pch = 21,                     # filled circles
     bg = "steelblue",             # fill color
     col = "white",                # border color
     cex = 1.5,                    # point size
     ylim = c(-0.5, 0.5),          # vertical spacing
     xlim = c(0, 10),
     main = "Poisson Process on [0, 10]",
     xlab = "x",
     ylab = "",
     yaxt = "n")                    

# add a horizontal line for visual reference
abline(h = 0, col = "gray60", lty = 2)

```

```{r}
# slide 11 example
lam_tilde <- 7.05
a <- 0; b <- 15
Lambda_tilde <- lam_tilde * (b - a)

set.seed(123)
N <- rpois(1, Lambda_tilde)
X <- runif(N, min = 0, max = b)

# Compute thinning
R <- X/50 + 3*X^2/100
U <- runif(N)
Y <- numeric()
k <- 1
for (i in 1:N) {
  if (R[i] > lam_tilde * U[i]) {
    Y[k] <- X[i]
    k <- k + 1
  }
}

# rejected points
reject <- !X %in% Y

# plot
plot(NA, NA, xlim = c(a, b), ylim = c(-0.5, 0.5),
     xlab = "X", ylab = "",
     main = "Poisson Process via Thinning Method",
     yaxt = "n",  # remove y-axis
     cex.main = 1.3, font.main = 2)
points(X[reject], rep(0, sum(reject)), col = rgb(0.5, 0.5, 0.5, 0.6), pch = 19, cex = 1.5)
points(Y, rep(0, length(Y)), col = "red", pch = 19, cex = 2, lwd = 1.2)
grid(nx = NULL, ny = NULL, col = "lightgrey", lty = 2, lwd = 0.5)
legend("top", legend = c("Rejected", "Accepted"),
       col = c(rgb(0.5, 0.5, 0.5, 0.6), "red"),
       pch = 19, pt.cex = c(1.5, 2), bty = "n", ncol = 2)
```

```{r}
# # slide 13 example
set.seed(123)  # for reproducibility
N <- rpois(1, 200)
U1 <- runif(N, min = 0, max = 1)
X1 <- sqrt(4 * U1)
X2 <- runif(N, min = 0, max = 1)

# plot
plot(X1, X2, pch = 19, col = rgb(0.2, 0.5, 0.8, 0.6),
     cex = 1.5, xlab = expression(X[1]),
     ylab = expression(X[2]),        # y-axis label with subscript
     main = "Scatter Plot of X1 vs X2", 
     las = 1)                        # horizontal axis labels
grid(nx = NULL, ny = NULL, col = "lightgrey", lty = 2, lwd = 0.5)
abline(h = seq(0, 1, by = 0.2), v = seq(0, 2, by = 0.5), col = "lightgrey", lty = 3)
```